# Generated by Django 5.2.7 on 2025-10-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tanggal_bergabung', models.DateField(auto_now_add=True)),
                ('kategori', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=150)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('jumlah_tersedia', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Kembali', 'Kembali'), ('Terlambat', 'Terlambat')], default='Dipinjam', max_length=20)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anggota')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buku')),
            ],
        ),
    ]
