# Generated by Django 5.2.7 on 2025-10-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggota',
            options={'verbose_name': 'Anggota', 'verbose_name_plural': 'Daftar Anggota'},
        ),
        migrations.AlterModelOptions(
            name='buku',
            options={'verbose_name': 'Buku', 'verbose_name_plural': 'Daftar Buku'},
        ),
        migrations.AlterModelOptions(
            name='transaksi',
            options={'verbose_name': 'Transaksi', 'verbose_name_plural': 'Daftar Transaksi'},
        ),
    ]
